### ISSUE TITLE
Document CI/CD/k8s guidelines

### ISSUE THREAD

**Issue by cyborgshead** [bro-n-bro/cybernode#2]
@abitrolly commented on [Sat Jan 27 2018](https://github.com/cyberFund/cybernode-archive/issues/123)

Checklist for CI/CD setup for container delivery:

* [ ] each `master` commit builds `:nightly`
  * [x] cyber-search
  * [ ] cyber-markets
  * [ ] cyber-ui
* [ ] each tag commit builds `:latest` and versioned container

---

* [ ] Maintain mapping between repositories and docker containers
  * [ ] cyber-search
  * [ ] cyber-markets
  * [ ] cyber-ui

**Comment by abitrolly** [comment]
See also https://github.com/cyberFund/cybernode/issues/5

**Comment by abitrolly** [comment]
We are not ready to document CI/CD guidelines, because we've got two separate stories. One is that guys need to quickly test custom containers and branches and use `staging`, and another that we need a stable `staging` where everything works and we can at any time see what works and what is not.

We need to plan CI/CD workflow more thoroughly next sprint.
